### ISSUE TITLE
CRAN Submission - v2.3

### ISSUE THREAD

**Issue by colearendt** [jeremystan/tidyjson#104]
Submit new version to [CRAN](https://cran.r-project.org/web/packages/policies.html):

- [x] Consolidate NEWS & bump version
- [x] Revdep (no dependencies anymore, I do not think)
- [ ] Check --as-cran
- [ ] Submit

**Comment by zapster** [comment]
Seems like tidyjson was removed: https://cran.r-project.org/web/packages/tidyjson/

Any update on this?

**Comment by colearendt** [comment]
Wow!  Very good to know!  That definitely lights a little fire under this ticket :)  Thanks for the note.  I have been fiddling with revdep issues, but this is a push to just go ahead with the release!

**Comment by sbilge** [comment]
Are there any updates on tidyjson CRAN issue? Will it be available in CRAN?

**Comment by naevtamarkus** [comment]
Hi! Is there a possibility to have this issue solved? 
I would like to convince some people to use this library and am having a hard time explaining why it's not mainstream.
Thanks

**Comment by colearendt** [comment]
:sob: Yeah. Sorry. I need to knock this out. I think the simple explanation right now is we transferred ownership (to me) and I have been busy. I'll try to get to this soon!

**Comment by colearendt** [comment]
Closing in favor of #114 (v0.2.4). Hopefully we'll have this knocked out soon!
