### ISSUE TITLE
conda package - GitHub release

### ISSUE THREAD

**Issue by sbilge** [jeremystan/tidyjson#111]
I need to package tidyjson to bioconda. A permanent link or an official release is required to do so. I am using a specific commit of tidyjson (SHA1: d79f3ff0a3279adef07819af4ab572f9ba46f3c0), and there are no official releases at that point, or after. Will there be a GitHub release soon?

**Comment by colearendt** [comment]
@sbilge Sorry for the extreme delay here! I finished the release to CRAN and tagged the v0.2.4 release on GItHub. PR #116 will finalize things and get the release onto master.
