### ISSUE TITLE
Add compatibility with dplyr programming data masking

### ISSUE THREAD

**Issue by Daveyr** [jeremystan/tidyjson#129]
With dplyr verbs it is possible to redirect environment variables as data variables, for instance:

```
var_summary <- function(data, var) {
  data %>%
    summarise(n = n(), min = min({{ var }}), max = max({{ var }}))
}
```
It would be very helpful if tidyjson verbs could do the same, e.g.

```
jsonDF <- function(data, object){
  data %>%
    enter_object({{object}}) %>%
    spread_all()
}
```

**Comment by ramiromagno** [comment]
I second this.

**Comment by colearendt** [comment]
PR that implements this is up! Please give it a try and LMK if any issues! https://github.com/colearendt/tidyjson/pull/132

**Comment by ramiromagno** [comment]
Thank you for your lightning response!

Just a question: in your PR you use `rlang::quo`, should it not be `rlang::enquo`?

Suggestion: perhaps add a test too with the embrace operator (as opposed to having only the `!!!` operator).

**Comment by colearendt** [comment]
I thought I did add a test with the embrace operator?

Also, I think quos vs. enquos is the choice, and I don’t think enquos is needed (isn’t it for names?). I have to admit that I often forget the distinctions haha - you might be right. I’ll take a look later!

Sent from my iPhone

On Jan 2, 2021, at 11:10 AM, Ramiro Magno <notifications@github.com> wrote:

﻿

Thank you for your lightning response!

Just a question: in your PR you use rlang::quo, should it not be rlang::enquo?

Suggestion: perhaps add a test too with the embrace operator (as opposed to having only the !!! operator).
