### ISSUE TITLE
`enter_object` won't work inside function

### ISSUE THREAD

**Issue by ramiromagno** [jeremystan/tidyjson#130]
library(magrittr)
    library(dplyr)
    #> 
    #> Attaching package: 'dplyr'
    #> The following objects are masked from 'package:stats':
    #> 
    #>     filter, lag
    #> The following objects are masked from 'package:base':
    #> 
    #>     intersect, setdiff, setequal, union
    library(tidyjson)  
    #> 
    #> Attaching package: 'tidyjson'
    #> The following object is masked from 'package:stats':
    #> 
    #>     filter

    # Example 1: object name as barename: works.
    worldbank %>%
      enter_object(majorsector_percent) %>%
      gather_array %>%
      spread_all %>%
      select(-document.id, -array.index)
    #> # A tbl_json: 1,405 x 3 tibble with a "JSON" attribute
    #>    ..JSON                  Name                                    Percent
    #>    <chr>                   <chr>                                     <dbl>
    #>  1 "{\"Name\":\"Educat..." Education                                    46
    #>  2 "{\"Name\":\"Educat..." Education                                    26
    #>  3 "{\"Name\":\"Public..." Public Administration, Law, and Justice      16
    #>  4 "{\"Name\":\"Educat..." Education                                    12
    #>  5 "{\"Name\":\"Public..." Public Administration, Law, and Justice      70
    #>  6 "{\"Name\":\"Public..." Public Administration, Law, and Justice      30
    #>  7 "{\"Name\":\"Transp..." Transportation                              100
    #>  8 "{\"Name\":\"Health..." Health and other social services            100
    #>  9 "{\"Name\":\"Indust..." Industry and trade                           50
    #> 10 "{\"Name\":\"Indust..." Industry and trade                           40
    #> # … with 1,395 more rows

    # Example 2: object name as string: works.
    worldbank %>%
      enter_object('majorsector_percent') %>%
      gather_array %>%
      spread_all %>%
      select(-document.id, -array.index)
    #> # A tbl_json: 1,405 x 3 tibble with a "JSON" attribute
    #>    ..JSON                  Name                                    Percent
    #>    <chr>                   <chr>                                     <dbl>
    #>  1 "{\"Name\":\"Educat..." Education                                    46
    #>  2 "{\"Name\":\"Educat..." Education                                    26
    #>  3 "{\"Name\":\"Public..." Public Administration, Law, and Justice      16
    #>  4 "{\"Name\":\"Educat..." Education                                    12
    #>  5 "{\"Name\":\"Public..." Public Administration, Law, and Justice      70
    #>  6 "{\"Name\":\"Public..." Public Administration, Law, and Justice      30
    #>  7 "{\"Name\":\"Transp..." Transportation                              100
    #>  8 "{\"Name\":\"Health..." Health and other social services            100
    #>  9 "{\"Name\":\"Indust..." Industry and trade                           50
    #> 10 "{\"Name\":\"Indust..." Industry and trade                           40
    #> # … with 1,395 more rows

    # Example 3: inside a function, object name passed as string: does not work.
    enter <- function(tbl_json, object) {
      tbl_json %>%
        enter_object(object) %>%
        gather_array %>%
        spread_all %>%
        select(-document.id, -array.index)
    }

    enter(worldbank, object = 'majorsector_percent')
    #> # A tbl_json: 0 x 1 tibble with a "JSON" attribute
    #> # … with 1 variable: ..JSON <chr>

<sup>Created on 2021-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by colearendt** [comment]
PR that implements this is up! Please give it a try and LMK if any issues! https://github.com/colearendt/tidyjson/pull/132
