### ISSUE TITLE
updates for purrr 1.0.0

### ISSUE THREAD

**Issue by mps9506** [jeremystan/tidyjson#142]
Hi,

Just a question. I didn't see any issues on CRAN with your package with the purrr 1.0.0 but the changes are causing some test failures on my downstream package {rATTAINS} (https://github.com/mps9506/rATTAINS/pull/26). The dev version with #140 resolves issues for me and I'm interested if you plan on submitting a release to CRAN in the near future.

This would just help me plan on if I should temporarily remove those tests or if I can wait to submit to CRAN.

Thanks!
Michael

**Comment by colearendt** [comment]
Hey Michael! Thanks for reaching out! I totally dropped the ball here - I’ll try to get this pushed out today or tomorrow!

**Comment by colearendt** [comment]
Forgot CRAN is on vacation 😅 And running into issues with Winbuilder, so a bit delayed here unfortunately!
